import os
import logging
from datetime import datetime
import base64
import io
import cv2
import numpy as np
import joblib
from flask import Flask, render_template, request, redirect, url_for, flash, session, jsonify, send_file
from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash, check_password_hash
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from functools import wraps
from utils.image_processing import process_image, is_ct_scan_image
from datetime import datetime, timedelta, timezone
from flask_mail import Mail, Message
import google.generativeai as genai
genai.configure(api_key="GEMINI_API_KEY")
import google.generativeai as genai
import os
from flask import jsonify, request
from utils.custom_diet import generate_custom_diet
from werkzeug.utils import secure_filename
from collections import defaultdict, Counter
from flask import Flask, render_template, request, redirect, url_for, session, flash
from collections import defaultdict, Counter


def create_detailed_report_pdf(user, results):
    """
    Returns a BytesIO buffer containing the exact detailed PDF used by download_report.
    """
    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    cancer_type = results.get('cancer_type', 'N/A')
    cancer_stage = results.get('cancer_stage', 'N/A')
    confidence = results.get('confidence', 0.0)
    confidence_percentage = f"{confidence * 100:.2f}%"
    date_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    steps = results.get('steps', {})

    # --- PAGE 1 ---
    logo_path = os.path.join("static", "images", "college_logo.png")
    if os.path.exists(logo_path):
        try:
            pdf.drawImage(logo_path, 60, height - 100, width=70, height=70)
        except Exception:
            pass

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(150, height - 70, "City Engineering College")
    pdf.setFont("Helvetica", 11)
    pdf.drawString(150, height - 85, "Department of Artificial Intelligence and Machine Learning")
    pdf.drawString(150, height - 100, "Pancreatic Cancer Detection System using Image Processing and AI")

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(60, height - 130, "Project Members:")
    pdf.setFont("Helvetica", 11)
    pdf.drawString(180, height - 130, "Vishnu B, Keerthan S, Ujwal D, Mahesh Maruti Udoji")

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(60, height - 145, "Guide:")
    pdf.setFont("Helvetica", 11)
    pdf.drawString(180, height - 145, "Asst. Prof. Rajashree, Dept. of AIML")
    pdf.line(60, height - 155, 550, height - 155)

    # Patient details & summary
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(60, height - 175, "Patient Details")
    pdf.setFont("Helvetica", 12)
    y = height - 195
    pdf.drawString(80, y, f"Name: {user.name}")
    y -= 15
    pdf.drawString(80, y, f"Patient ID: {user.id}")
    y -= 15
    pdf.drawString(80, y, f"Age: {user.age}     Gender: {user.gender}")
    y -= 15
    pdf.drawString(80, y, f"Contact: {user.contact}")
    y -= 15
    pdf.drawString(80, y, f"Date: {date_time}")
    y -= 20
    pdf.line(60, y, 550, y)
    y -= 20

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(60, y, "Health Report Summary")
    pdf.setFont("Helvetica", 12)
    y -= 20
    pdf.drawString(80, y, f"Cancer Type: {cancer_type}")
    y -= 18
    pdf.drawString(80, y, f"Cancer Stage: {cancer_stage}")
    y -= 18
    pdf.drawString(80, y, f"Confidence: {confidence_percentage}")
    y -= 25
    pdf.line(60, y, 550, y)
    y -= 18

    # Diet & Exercise (always include — it's fine for healthy too)
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(60, y, "Dietary Recommendations:")
    pdf.setFont("Helvetica", 11)
    y -= 18
    diet = [
        "Eat fresh fruits, steamed vegetables, and whole grains.",
        "Include lean proteins like fish, tofu, and lentils.",
        "Avoid fried, oily, and spicy foods.",
        "Stay hydrated throughout the day."
    ]
    for line in diet:
        pdf.drawString(80, y, f"• {line}")
        y -= 15

    y -= 8
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(60, y, "Exercise Recommendations:")
    pdf.setFont("Helvetica", 11)
    y -= 18
    exercises = [
        "Brisk walking or cycling for 30 mins daily.",
        "Yoga poses like Bhujangasana and Vajrasana.",
        "Light strength training under supervision."
    ]
    for line in exercises:
        pdf.drawString(80, y, f"• {line}")
        y -= 15

    # Footer on page 1
    pdf.setFont("Helvetica-Oblique", 10)
    pdf.drawString(60, 100, "Generated by Pancreatic Cancer Detection System – City Engineering College")
    pdf.drawString(60, 85, "For educational and research purposes only.")

    # --- PAGE 2: 2x2 image grid ---
    pdf.showPage()
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(200, height - 60, "CT Scan Image Results")
    pdf.line(60, height - 70, 550, height - 70)

    # grid parameters (smaller images so 2x2 fits)
    img_width, img_height = 200, 140
    x_positions = [80, 320]
    y_positions = [height - 150, height - 340]

    image_titles = [
        ("original", "Original CT Scan"),
        ("preprocessed", "Preprocessed CT Scan"),
        ("segmented", "Segmented Image"),
        ("features", "Feature-Detected Image")
    ]

    index = 0
    for row_y in y_positions:
        for col_x in x_positions:
            if index >= len(image_titles):
                break
            key, title = image_titles[index]
            img = steps.get(key)
            if img is not None:
                try:
                    # normalize channels
                    if len(img.shape) == 2:
                        img_rgb = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
                    elif img.shape[2] == 4:
                        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGRA2RGB)
                    else:
                        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

                    _, buf_img = cv2.imencode(".jpg", img_rgb)
                    image_data = ImageReader(io.BytesIO(buf_img.tobytes()))
                    pdf.drawImage(image_data, col_x, row_y - img_height, width=img_width, height=img_height)
                    pdf.setFont("Helvetica", 11)
                    pdf.drawCentredString(col_x + img_width / 2, row_y - img_height - 12, title)
                except Exception as e:
                    print("Image draw error:", e)
            index += 1

    # footer on page 2
    pdf.setFont("Helvetica-Oblique", 10)
    pdf.drawString(60, 85, "Generated by Pancreatic Cancer Detection System – City Engineering College")

    pdf.save()
    buffer.seek(0)
    return buffer


# -------------------------------
# FLASK APP CONFIGURATION
# -------------------------------
app = Flask(__name__)
app.secret_key = 'supersecretkey'

@app.context_processor
def inject_user():
    return dict(user_id=session.get('user_id'), user_name=session.get('user_name'))


# Database setup
import os

app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get("DATABASE_URL")
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)

# ML model
model = joblib.load("pancreas_model.pkl")

# Logging setup
logging.basicConfig(level=logging.DEBUG)
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}

last_results = None  # Global variable for report download

# -------------------------------
# LOGIN REQUIRED DECORATOR
# -------------------------------
def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user_id' not in session:
            flash('⚠️ Please log in to access this page.', 'warning')
            return redirect(url_for('login', next=request.endpoint))
        return f(*args, **kwargs)
    return decorated_function


def to_ist(utc_dt):
    if utc_dt is None:
        return None
    ist_offset = timedelta(hours=5, minutes=30)
    return utc_dt + ist_offset

@app.context_processor
def inject_helpers():
    return dict(to_ist=to_ist)
# -------------------------------
# DATABASE MODEL
# -------------------------------
class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(100), unique=True, nullable=False)
    password = db.Column(db.String(200), nullable=False)
    gender = db.Column(db.String(20), nullable=False)
    age = db.Column(db.Integer, nullable=False)
    contact = db.Column(db.String(15), nullable=False)
    scans = db.relationship('ScanHistory', backref='user', lazy=True , cascade="all, delete-orphan")

class Scan(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    image_path = db.Column(db.String(300))
    cancer_type = db.Column(db.String(100))
    cancer_stage = db.Column(db.String(50))
    confidence = db.Column(db.Float)
    cancer_detected = db.Column(db.Boolean)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)

    user = db.relationship('User', backref='user_scans')

class Doctor(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150), nullable=False)
    email = db.Column(db.String(150), unique=True, nullable=False)
    password = db.Column(db.String(200), nullable=False)
    specialization = db.Column(db.String(120), nullable=False)   # ✅ ADD THIS
    contact = db.Column(db.String(20), nullable=False)
    medical_id = db.Column(db.String(120), nullable=False)       # ADD
    id_proof_path = db.Column(db.String(250), nullable=False)  
    status = db.Column(db.String(20), default="PENDING")   # Pending, Approved, Rejected
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

  
class ScanHistory(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    
    cancer_type = db.Column(db.String(100))
    cancer_stage = db.Column(db.String(50))
    cancer_detected = db.Column(db.Boolean, nullable=False)
    confidence = db.Column(db.Float, nullable=False)
    date = db.Column(db.DateTime, default=datetime.utcnow)
# -------------------------------
# USER AUTH ROUTES
# -------------------------------
@app.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        name = request.form['name']
        email = request.form['email']
        password = request.form['password']
        gender = request.form['gender']
        age = request.form['age']
        contact = request.form['contact']

        existing_user = User.query.filter_by(email=email).first()
        if existing_user:
            flash('⚠️ Email already registered. Please log in.', 'warning')
            return redirect(url_for('login'))

        hashed_password = generate_password_hash(password, method='pbkdf2:sha256')
        new_user = User(name=name, email=email, password=hashed_password,
                        gender=gender, age=age, contact=contact)
        db.session.add(new_user)
        db.session.commit()
        flash('✅ Account created successfully! Please log in.', 'success')
        return redirect(url_for('login'))
    return render_template('signup.html')

@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        user = User.query.filter_by(email=email).first()
        if user and check_password_hash(user.password, password):
            session['user_id'] = user.id
            session['user_name'] = user.name
            flash(f'👋 Welcome, {user.name}!', 'success')
            return redirect(url_for('dashboard'))

        else:
            flash('❌ Invalid email or password.', 'danger')
    return render_template('login.html')

@app.route('/logout')
def logout():
    session.clear()
    flash('👋 Logged out successfully.', 'info')
    return redirect(url_for('login'))

@app.route('/users')
@login_required
def view_users():
    # Optional: Restrict this to admin
    if session.get('user_name') != "Vishnu B":
        flash("🚫 Access denied. Only admin can view user data.", "danger")
        return redirect(url_for('process'))
    users = User.query.all()
    return render_template('users.html', users=users)

# -------------------------------
# HELPER FUNCTIONS
# -------------------------------
def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS
# -------------------------------
# MAIL FUNCTIONS
# -------------------------------
app.config['MAIL_SERVER'] = 'smtp.gmail.com'
app.config['MAIL_PORT'] = 587
app.config['MAIL_USE_TLS'] = True
app.config['MAIL_USERNAME'] = 'yourmedicalreport@gmail.com'         # 🔹 Replace with your email
app.config['MAIL_PASSWORD'] = 'fwzbyfbushrjbfma'       # 🔹 Use App Password (not your Gmail password!)
app.config['MAIL_DEFAULT_SENDER'] = ('Pancreatic Detection', 'yourmedicalreport@gmail.com')

mail = Mail(app)

# -------------------------------
# ROUTES
# -------------------------------
@app.route('/')
def index():
    return render_template('index.html')

@app.route('/process')
@login_required
def process():
    return render_template('process.html')


@app.route('/dashboard')
def dashboard():
    if 'user_id' not in session:
        flash('⚠️ Please log in to access your dashboard.', 'warning')
        return redirect(url_for('login'))

    user_id = session['user_id']
    user = User.query.get(user_id)
    scans = ScanHistory.query.filter_by(user_id=user_id).order_by(ScanHistory.date.desc()).all()
    return render_template('dashboard.html', user=user, scans=scans)


@app.route('/about')
def about():
    return render_template('about.html')

# -------------------------------
# IMAGE ANALYSIS ROUTE
# -------------------------------
@app.route('/analyze', methods=['POST'])
@login_required
def analyze():
    global last_results
    if 'image' not in request.files:
        return jsonify({'error': 'No image uploaded'}), 400

    file = request.files['image']
    if file.filename == '' or not allowed_file(file.filename):
        return jsonify({'error': 'Invalid file type'}), 400

    try:
        img_stream = file.read()
        nparr = np.frombuffer(img_stream, np.uint8)
        img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
        if img is None:
            return jsonify({'error': 'Failed to decode image'}), 400

        if not is_ct_scan_image(img):
            return jsonify({'error': 'This is not a CT or MRI scan image. Please upload a grayscale medical scan.'}), 400

        # --- Process Image ---
        results = process_image(img)
        confidence = float(results.get('confidence', 0))
        cancer_type = results.get('cancer_type', 'Unknown').strip()

        # --- Stage Detection Logic ---
        cancer_type_str = cancer_type.lower().strip()
        benign_keywords = ["healthy", "non-cancer", "normal", "no cancer", "benign", "no tumor", "no abnormality", "noncancerous"]

        if any(k in cancer_type_str for k in benign_keywords) or confidence < 0.5:
            cancer_stage = "No Cancer Detected"
        elif 0.5 <= confidence < 0.7:
            cancer_stage = "Stage I"
        elif 0.7 <= confidence < 0.85:
            cancer_stage = "Stage II"
        elif 0.85 <= confidence < 0.95:
            cancer_stage = "Stage III"
        else:
            cancer_stage = "Stage IV"

        # --- Save Results Globally and in Session ---
        last_results = {
            'cancer_type': cancer_type,
            'cancer_stage': cancer_stage,
            'confidence': confidence,
            'steps': results['steps']
        }

        session['last_results'] = {
            'cancer_type': cancer_type,
            'cancer_stage': cancer_stage,
            'confidence': confidence
        }

        # --- Save Scan History ---
        user_id = session.get('user_id')
        user = User.query.get(user_id)
        cancer_detected_flag = not any(k in cancer_type.lower() for k in benign_keywords)
        new_scan = ScanHistory(
            user_id=user_id,
            cancer_type=cancer_type,
            cancer_stage=cancer_stage,
            cancer_detected=cancer_detected_flag,
            confidence=confidence
        )
        db.session.add(new_scan)
        db.session.commit()

        # --- Generate New Detailed PDF (same one you download) ---
        pdf_buffer = io.BytesIO()
        pdf_buffer = create_detailed_report_pdf(user, last_results)

        # --- Send the Same Detailed Report via Email ---
        import smtplib
        from email.mime.multipart import MIMEMultipart
        from email.mime.text import MIMEText
        from email.mime.base import MIMEBase
        from email import encoders

        sender_email = "MAIL_USERNAME"
        sender_password = "MAIL_PASSWORD"
        receiver_email = user.email

        msg = MIMEMultipart()
        msg["From"] = sender_email
        msg["To"] = receiver_email
        msg["Subject"] = "Your Pancreatic Cancer Detection Detailed Report"

        body = f"""
        Hello {user.name},

        Your CT scan has been analyzed successfully.

        🧠 Cancer Type: {cancer_type}
        🏥 Cancer Stage: {cancer_stage}
        📊 Confidence: {confidence * 100:.2f}%

        Please find the attached detailed report containing your analysis results, diet, exercise suggestions, and CT scan images.

        Regards,  
        City Engineering College  
        Department of Artificial Intelligence and Machine Learning
        """
        msg.attach(MIMEText(body, "plain"))

        # Attach the same PDF as sent to frontend
        attachment = MIMEBase("application", "pdf")
        attachment.set_payload(pdf_buffer.getvalue())
        encoders.encode_base64(attachment)
        attachment.add_header("Content-Disposition", "attachment", filename="Detailed_Health_Report.pdf")
        msg.attach(attachment)

        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.send_message(msg)

        # --- Encode images for Frontend Display ---
        processed_images = {}
        for step, image in results['steps'].items():
            _, buffer = cv2.imencode('.jpg', image)
            img_str = base64.b64encode(buffer).decode('utf-8')
            processed_images[step] = f"data:image/jpeg;base64,{img_str}"

        return jsonify({
            'success': True,
            'processed_images': processed_images,
            'cancer_type': cancer_type,
            'cancer_stage': cancer_stage,
            'confidence': confidence
        })

    except Exception as e:
        logging.exception("❌ Error in /analyze: %s", e)
        return jsonify({'error': f'Error processing image: {str(e)}'}), 500
    
    
@app.route('/contact', methods=['GET', 'POST'])
def contact():
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        subject = request.form.get('subject')
        message = request.form.get('message')

        # 📧 Prepare email content
        body = f"""
        📩 New message received from PancreScan Contact Form:

        👤 Name: {name}
        📧 Email: {email}
        📝 Subject: {subject}
        💬 Message:
        {message}
        """

        try:
            import smtplib
            from email.mime.text import MIMEText
            from email.mime.multipart import MIMEMultipart

            sender_email = "MAIL_USERNAME"
            sender_password = "MAIL_PASSWORD"  # Replace with your Gmail App Password
            receiver_email = "MAIL_USERNAME"

            msg = MIMEMultipart()
            msg['From'] = sender_email
            msg['To'] = receiver_email
            msg['Subject'] = f"📬 New Contact Message: {subject}"
            msg.attach(MIMEText(body, 'plain'))

            with smtplib.SMTP('smtp.gmail.com', 587) as server:
                server.starttls()
                server.login(sender_email, sender_password)
                server.send_message(msg)

            flash("✅ Your message has been sent successfully!", "success")

        except Exception as e:
            print("❌ Email sending failed:", e)
            flash("❌ Failed to send message. Please try again later.", "danger")

        return redirect(url_for('contact'))

    return render_template('contact.html')

@app.route("/custom_diet")
def custom_diet():

    if "user_id" not in session:
        return jsonify({"diet": ["⚠️ Please log in to view personalised diet."]})

    user = User.query.get(session["user_id"])

    if not user:
        return jsonify({"diet": ["⚠️ User not found."]})

    # Count total scans
    scan_count = ScanHistory.query.filter_by(user_id=user.id).count()

    # Check if last scan had cancer
    last_scan = ScanHistory.query.filter_by(user_id=user.id).order_by(ScanHistory.date.desc()).first()
    cancer_detected = False
    if last_scan:
        cancer_detected = last_scan.cancer_detected

    # Generate personalised diet
    diet = generate_custom_diet(
        age=user.age,
        gender=user.gender,
        scan_count=scan_count,
        cancer_detected=cancer_detected
    )

    return jsonify({"diet": diet})

@app.route("/custom_exercise")
def custom_exercise():
    user_id = session.get("user_id")
    user = User.query.get(user_id)

    # Use date instead of timestamp
    last_scan = ScanHistory.query.filter_by(user_id=user_id).order_by(ScanHistory.date.desc()).first()
    cancer_detected = (last_scan.cancer_detected == "Yes") if last_scan else False

    age = user.age if user else 30
    gender = user.gender if user else "other"

    exercises = []

    # --- Age Based ---
    if age < 25:
        exercises.append("🏃‍♂️ 20–30 min jogging to boost overall fitness.")
        exercises.append("🚴 Cycling to improve stamina and metabolism.")
    elif 25 <= age < 40:
        exercises.append("🏋️ Strength training 3x/week for metabolic balance.")
        exercises.append("🧘 Yoga for flexibility & stress reduction.")
    elif 40 <= age < 60:
        exercises.append("🚶 Brisk walking for 30 minutes daily.")
        exercises.append("🧘‍♂️ Deep breathing + Pranayama for pancreas support.")
    else:
        exercises.append("🚶 Light walking 20 minutes/day.")
        exercises.append("🧘 Gentle stretching & chair yoga.")

    # --- Gender Based ---
    if gender.lower() == "male":
        exercises.append("💪 Upper-body strengthening with resistance bands.")
    elif gender.lower() == "female":
        exercises.append("🦵 Leg-strengthening & low-impact aerobic exercises.")
    else:
        exercises.append("✨ Balanced low-impact movements suitable for all.")

    # --- Cancer-based ---
    if cancer_detected:
        exercises.append("🧘‍♂️ Do soft yoga poses (Cobra, Child Pose, Cat-Cow).")
        exercises.append("🚶 Prefer gentle walking over intense cardio.")
    else:
        exercises.append("🏃 Maintain a healthy mix of cardio + stretching.")

    return jsonify({"exercises": exercises})

# -------------------------------
# REPORT DOWNLOAD ROUTE
# -------------------------------
@app.route('/download_report', methods=['POST'])
@login_required
def download_report():
    global last_results
    if not last_results:
        return jsonify({'error': 'No image data available for report'}), 400

    data = request.get_json() if request.is_json else session.get('last_results', {})
    user_id = session.get('user_id')
    user = User.query.get(user_id)

    cancer_type = data.get('cancer_type', 'N/A')
    cancer_stage = data.get('cancer_stage', 'N/A')
    confidence = data.get('confidence', 0)
    confidence_percentage = f"{confidence * 100:.2f}%"
    date_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # ================= PAGE 1 =================
    logo_path = os.path.join("static", "images", "college_logo.png")
    if os.path.exists(logo_path):
        pdf.drawImage(logo_path, 60, height - 100, width=70, height=70)

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(150, height - 70, "City Engineering College")
    pdf.setFont("Helvetica", 11)
    pdf.drawString(150, height - 85, "Department of Artificial Intelligence and Machine Learning")
    pdf.drawString(150, height - 100, "Pancreatic Cancer Detection System using Image Processing and AI")

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(60, height - 130, "Project Members:")
    pdf.setFont("Helvetica", 11)
    pdf.drawString(180, height - 130, "Vishnu B, Keerthan S, Ujwal D, Mahesh Maruti Udoji")

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(60, height - 145, "Guide:")
    pdf.setFont("Helvetica", 11)
    pdf.drawString(180, height - 145, "Asst. Prof. Rajashree, Dept. of AIML")

    pdf.line(60, height - 155, 550, height - 155)

    # ----- Patient Details -----
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(60, height - 175, "Patient Details")
    pdf.setFont("Helvetica", 12)
    y = height - 195
    pdf.drawString(80, y, f"Name: {user.name}")
    y -= 15
    pdf.drawString(80, y, f"Patient ID: {user.id}")
    y -= 15
    pdf.drawString(80, y, f"Age: {user.age}     Gender: {user.gender}")
    y -= 15
    pdf.drawString(80, y, f"Contact: {user.contact}")
    y -= 15
    pdf.drawString(80, y, f"Date: {date_time}")
    y -= 20
    pdf.line(60, y, 550, y)
    y -= 20

    # ----- Health Report Summary -----
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(60, y, "Health Report Summary")
    pdf.setFont("Helvetica", 12)
    y -= 20
    pdf.drawString(80, y, f"Cancer Type: {cancer_type}")
    y -= 20
    pdf.drawString(80, y, f"Cancer Stage: {cancer_stage}")
    y -= 20
    pdf.drawString(80, y, f"Confidence: {confidence_percentage}")
    y -= 30
    pdf.line(60, y, 550, y)
    y -= 20

    # ----- Diet & Exercise -----
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(60, y, "Dietary Recommendations:")
    pdf.setFont("Helvetica", 11)
    y -= 20
    diet = [
        "✔ Eat fresh fruits, steamed vegetables, and whole grains.",
        "✔ Include lean proteins like fish, tofu, and lentils.",
        "✔ Avoid fried, oily, and spicy foods.",
        "✔ Stay hydrated throughout the day."
    ]
    for line in diet:
        pdf.drawString(80, y, line)
        y -= 18

    y -= 10
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(60, y, "Exercise Recommendations:")
    pdf.setFont("Helvetica", 11)
    y -= 20
    exercises = [
        "🏃 Brisk walking or cycling for 30 mins daily.",
        "🧘 Yoga poses like Bhujangasana and Vajrasana.",
        "🏋️ Light strength training under supervision."
    ]
    for line in exercises:
        pdf.drawString(80, y, line)
        y -= 18

    # ----- Footer -----
    pdf.setFont("Helvetica-Oblique", 10)
    pdf.drawString(60, 100, "Generated by Pancreatic Cancer Detection System – City Engineering College")
    pdf.drawString(60, 85, "For educational and research purposes only.")

    # ================= PAGE 2 =================
    pdf.showPage()
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(200, height - 60, "CT Scan Image Results")
    pdf.line(60, height - 70, 550, height - 70)

    # Define image titles and order
    image_titles = [
        ("original", "Original CT Scan"),
        ("preprocessed", "Preprocessed CT Scan"),
        ("segmented", "Segmented Image"),
        ("features", "Feature-Detected Image")
    ]

    # Coordinates for grid positions
    img_width, img_height = 200, 140  # smaller consistent size
    x_positions = [80, 320]  # left and right columns
    y_positions = [height - 150, height - 340]  # row 1, row 2

    # Draw 2x2 grid of images
    index = 0
    for row, y_pos in enumerate(y_positions):
        for col, x_pos in enumerate(x_positions):
            if index >= len(image_titles):
                break
            key, title = image_titles[index]
            image = last_results['steps'].get(key)

            if image is not None:
                try:
                    # Convert color space safely
                    if len(image.shape) == 2:
                        image_rgb = cv2.cvtColor(image, cv2.COLOR_GRAY2RGB)
                    elif image.shape[2] == 4:
                        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGRA2RGB)
                    else:
                        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

                    _, buffer_img = cv2.imencode(".jpg", image_rgb)
                    image_data = ImageReader(io.BytesIO(buffer_img.tobytes()))

                    pdf.drawImage(image_data, x_pos, y_pos - img_height, width=img_width, height=img_height)
                    pdf.setFont("Helvetica", 11)
                    pdf.drawCentredString(x_pos + img_width / 2, y_pos - img_height - 15, title)
                except Exception as e:
                    print(f"⚠️ Error drawing image {title}: {e}")

            index += 1

    # Page 2 footer
    pdf.setFont("Helvetica-Oblique", 10)
    pdf.drawString(60, 85, "Generated by Pancreatic Cancer Detection System – City Engineering College")

    pdf.save()
    buffer.seek(0)

    return send_file(buffer, as_attachment=True, download_name="Health_Report.pdf", mimetype='application/pdf')



import os
import google.generativeai as genai
from flask import request, jsonify

# ==============================
# 🔐 Gemini Configuration
# ==============================
genai.configure(api_key="GEMINI_API_KEY")

# ==============================
# 💬 Chatbot Route (using Gemini 2.5 Flash)
# ==============================
@app.route('/chatbot', methods=['POST'])
def chatbot():
    try:
        data = request.get_json()
        user_msg = data.get("message", "").strip()

        if not user_msg:
            return jsonify({"reply": "Please type a message 😊"})

        # ✅ Use the correct, available model from your list
        model = genai.GenerativeModel("models/gemini-2.5-flash")

        prompt = f"""
        You are an AI health assistant for a project titled
        'Pancreatic Cancer Detection using Image Processing and AI'
        by City Engineering College.

        Your role:
        - Help users understand cancer stages, confidence scores, and results.
        - Offer general guidance on diet, exercise, and healthy habits.
        - Be educational and polite.
        - Do not give prescriptions or medical treatments.

        User: {user_msg}
        """

        response = model.generate_content(prompt)
        reply = response.text or "Sorry, I couldn't generate a response."

        return jsonify({"reply": reply})

    except Exception as e:
        print(f"❌ Chatbot error: {e}")
        return jsonify({"reply": "⚠️ Something went wrong. Please try again later."})

@app.route('/download_basic_report', methods=['POST'])
@login_required
def download_basic_report():
    try:
        user_id = session.get('user_id')
        user = User.query.get(user_id)

        # ✅ Get scan_id from form (each row sends its own scan_id)
        scan_id = request.form.get("scan_id")
        scan = ScanHistory.query.get(scan_id)

        if not scan:
            flash("⚠️ Scan not found.", "warning")
            return redirect(url_for('dashboard'))

        # Extract analysis data from the selected scan
        cancer_type = scan.cancer_type or "N/A"
        cancer_stage = scan.cancer_stage or "N/A"
        confidence = scan.confidence or 0.0
        confidence_percentage = f"{confidence * 100:.2f}%"
        cancerous = scan.cancer_detected

        # Prepare PDF
        buffer = io.BytesIO()
        pdf = canvas.Canvas(buffer, pagesize=letter)
        width, height = letter

        # ======================
        # HEADER SECTION
        # ======================
        logo_path = os.path.join("static", "images", "college_logo.png")
        if os.path.exists(logo_path):
            pdf.drawImage(logo_path, 60, height - 100, width=70, height=70)

        pdf.setFont("Helvetica-Bold", 16)
        pdf.drawString(150, height - 70, "City Engineering College")
        pdf.setFont("Helvetica", 11)
        pdf.drawString(150, height - 85, "Department of Artificial Intelligence and Machine Learning")
        pdf.drawString(150, height - 100, "Pancreatic Cancer Detection System using Image Processing and AI")

        pdf.setFont("Helvetica-Bold", 12)
        pdf.drawString(60, height - 130, "Project Members:")
        pdf.setFont("Helvetica", 11)
        pdf.drawString(180, height - 130, "Vishnu B, Keerthan S, Ujwal D, Mahesh Maruti Udoji")
        pdf.setFont("Helvetica-Bold", 12)
        pdf.drawString(60, height - 145, "Guide:")
        pdf.setFont("Helvetica", 11)
        pdf.drawString(180, height - 145, "Asst. Prof. Rajashree, Dept. of AIML")

        pdf.line(60, height - 155, 550, height - 155)

        # ======================
        # PATIENT DETAILS
        # ======================
        pdf.setFont("Helvetica-Bold", 14)
        pdf.drawString(60, height - 175, "Patient Details")
        pdf.line(60, height - 180, 550, height - 180)
        pdf.setFont("Helvetica", 12)
        y = height - 200
        pdf.drawString(80, y, f"Patient Name: {user.name}")
        y -= 15
        pdf.drawString(80, y, f"Patient ID: {user.id}")
        y -= 15
        pdf.drawString(80, y, f"Age: {user.age}     Gender: {user.gender}")
        y -= 15
        pdf.drawString(80, y, f"Contact Number: {user.contact}")
        y -= 15
        pdf.drawString(80, y, f"Date: {scan.date.strftime('%Y-%m-%d')}")
        y -= 25
        pdf.line(60, y, 550, y)
        y -= 25

        # ======================
        # SCAN SUMMARY
        # ======================
        pdf.setFont("Helvetica-Bold", 14)
        pdf.drawString(60, y, "Scan Analysis Summary")
        y -= 20
        pdf.setFont("Helvetica", 12)
        pdf.drawString(80, y, f"🧠 Cancer Type: {cancer_type}")
        y -= 20
        pdf.drawString(80, y, f"🏥 Cancer Stage: {cancer_stage}")
        y -= 20
        pdf.drawString(80, y, f"📊 Confidence: {confidence_percentage}")
        y -= 25
        pdf.line(60, y, 550, y)
        y -= 20

        # ======================
        # RECOMMENDATIONS (if cancerous)
        # ======================
        if cancerous:
            pdf.setFont("Helvetica-Bold", 14)
            pdf.drawString(60, y, "Diet and Exercise Recommendations")
            y -= 20
            pdf.setFont("Helvetica", 12)

            # Diet
            pdf.drawString(70, y, "✅ Recommended Diet:")
            y -= 15
            diet_points = [
                "Fresh fruits like apples, papaya, berries, oranges.",
                "Steamed vegetables: spinach, broccoli, carrots, beans.",
                "Lean proteins: fish, tofu, lentils, boiled chicken.",
                "Whole grains: oats, brown rice, quinoa.",
                "Healthy fats: olive oil, avocados, nuts (moderate).",
                "Stay hydrated and drink herbal teas."
            ]
            for item in diet_points:
                pdf.drawString(90, y, f"• {item}")
                y -= 15

            y -= 10
            pdf.drawString(70, y, "🚫 Foods to Avoid:")
            y -= 15
            avoid_points = [
                "Fried and processed foods.",
                "High-fat dairy and red meats.",
                "Refined sugar, alcohol, and soft drinks.",
                "Spicy or oily foods that affect digestion."
            ]
            for item in avoid_points:
                pdf.drawString(90, y, f"• {item}")
                y -= 15

            y -= 10
            pdf.drawString(70, y, "🏋️ Recommended Exercises:")
            y -= 15
            exercise_points = [
                "Brisk walking – 30 mins daily.",
                "Light jogging or swimming.",
                "Yoga poses: Bhujangasana, Dhanurasana, Vajrasana.",
                "Deep breathing (Pranayama) and relaxation routines."
            ]
            for item in exercise_points:
                pdf.drawString(90, y, f"• {item}")
                y -= 15

            y -= 10
            pdf.line(60, y, 550, y)
            y -= 20

        # ======================
        # FOOTER
        # ======================
        pdf.setFont("Helvetica-Oblique", 10)
        pdf.drawString(60, 60, "Note: This is a basic generated report. For a detailed report, upload your scan again.")
        pdf.drawString(60, 40, "Generated by Pancreatic Cancer Detection System – City Engineering College")
        pdf.drawString(60, 30, "For educational and research purposes.")

        pdf.save()
        buffer.seek(0)

        return send_file(
            buffer,
            as_attachment=True,
            download_name=f"Basic_Report_Scan_{scan.id}.pdf",
            mimetype="application/pdf"
        )

    except Exception as e:
        logging.exception("❌ Error generating basic report: %s", e)
        flash("❌ Failed to generate report. Please try again.", "danger")
        return redirect(url_for('dashboard'))
@app.route("/doctor_dashboard")
def doctor_dashboard():
    if "doctor_id" not in session:
        flash("Please login first.", "warning")
        return redirect(url_for("doctor_login"))

    doctor = Doctor.query.get(session.get("doctor_id"))

    # If doctor not found
    if doctor is None:
        session.pop("doctor_id", None)
        flash("Your session expired. Please login again.", "warning")
        return redirect(url_for("doctor_login"))

    # Rejected doctor
    if doctor.status == "REJECTED":
        return render_template(
            "rejected.html",
            message="Your account has been rejected. Contact us at yourmedicalreport@gmail.com"
        )

    # Pending doctor
    if doctor.status == "PENDING":
        return render_template(
            "pending.html",
            message="Your account is pending admin approval."
        )

    # Get all scans
    scans = ScanHistory.query.all()

    # Build chart data: cancer cases per user
    user_stats = {}

    for s in scans:
        if s.user:  # make sure user exists
            uid = s.user.id

            # initialize user entry
            if uid not in user_stats:
                user_stats[uid] = {
                    "id": uid,
                    "name": s.user.name,
                    "cancer_count": 0
                }

            # add cancer count
            if s.cancer_detected:
                user_stats[uid]["cancer_count"] += 1

    # Convert dict -> list
    chart_data = list(user_stats.values())

    print("CHART DATA:", chart_data)  # DEBUG

    return render_template(
        "doctor_dashboard.html",
        doctor=doctor,
        scans=scans,
        chart_data=chart_data
    )



@app.route('/doctor_register', methods=['GET', 'POST'])
def doctor_register():
    if request.method == 'POST':
        name = request.form['name']
        email = request.form['email']
        contact = request.form['contact']
        specialization = request.form['specialist']
        medical_id = request.form['medical_id']
        password = generate_password_hash(request.form['password'], method='pbkdf2:sha256')

        # -----------------------------
        #  ID PROOF UPLOAD (FIXED)
        # -----------------------------
        id_file = request.files['id_proof']
        filename = secure_filename(id_file.filename)

        # Create folder: static/uploads/doctor_ids/
        upload_folder = os.path.join(app.root_path, "static", "uploads", "doctor_ids")

        os.makedirs(upload_folder, exist_ok=True)

        # Save file to static/uploads/doctor_ids/filename.jpg
        save_path = os.path.join(upload_folder, filename)
        id_file.save(save_path)

        # Store ONLY relative path (NO "static/" here)
        id_proof_path = f"uploads/doctor_ids/{filename}"


        # -----------------------------
        #  SAVE DOCTOR RECORD
        # -----------------------------
        new_doctor = Doctor(
            name=name,
            email=email,
            contact=contact,
            specialization=specialization,
            medical_id=medical_id,
            password=password,
            id_proof_path=id_proof_path,   # Correct path stored
            status="PENDING"
        )

        db.session.add(new_doctor)
        db.session.commit()

        flash("📝 Registration submitted! Wait for admin approval.", "info")
        return redirect(url_for('doctor_login'))

    return render_template("doctor_register.html")
@app.route('/fix_paths')
def fix_paths():
    for d in Doctor.query.all():
        path = d.id_proof_path

        # remove double uploads/
        path = path.replace("uploads/uploads/", "uploads/")

        # replace windows slashes
        path = path.replace("\\", "/")

        d.id_proof_path = path

    db.session.commit()
    return "Paths fixed!"

@app.route('/doctor_login', methods=['GET', 'POST'])
def doctor_login():
    if request.method == "POST":
        email = request.form['email']
        password = request.form['password']

        doctor = Doctor.query.filter_by(email=email).first()

        if doctor and check_password_hash(doctor.password, password):
            if doctor.status != "APPROVED":
                flash("Your account is not approved by admin yet.", "danger")
                return redirect(url_for('doctor_login'))

            session['doctor_id'] = doctor.id
            
            flash(f"Welcome Dr. {doctor.name}", "success")
            return redirect(url_for('doctor_dashboard'))

        flash("Invalid credentials", "danger")

    return render_template("doctor_login.html")

@app.route('/approve_doctor/<int:doctor_id>')
def approve_doctor(doctor_id):
    doctor = Doctor.query.get(doctor_id)
    doctor.status = "APPROVED"
    db.session.commit()
    flash("✔ Doctor approved!", "success")
    return redirect(url_for('admin_panel'))


@app.route('/reject_doctor/<int:doctor_id>')
def reject_doctor(doctor_id):
    doctor = Doctor.query.get(doctor_id)
    doctor.status = "REJECTED"
    db.session.commit()
    flash("❌ Doctor rejected!", "danger")
    return redirect(url_for('admin_panel'))
@app.route('/doctor/user/<int:user_id>')
def doctor_view_user(user_id):
    if 'doctor_id' not in session:
        flash("⚠️ Please log in as doctor.", "warning")
        return redirect(url_for('doctor_login'))
    doctor = Doctor.query.get(session["doctor_id"])
    user = User.query.get(user_id)
    if not user:
        flash("User not found.", "danger")
        return redirect(url_for('doctor_dashboard'))

    scans = ScanHistory.query.filter_by(user_id=user_id).order_by(ScanHistory.date.desc()).all()

    total_scans = len(scans)
    cancer_detected = sum(1 for s in scans if s.cancer_detected)
    last_scan = scans[0] if scans else None

    return render_template(
        "doctor_view_user.html",
        user=user,
        doctor=doctor,
        total_scans=total_scans,
        cancer_detected=cancer_detected,
        last_scan=last_scan
    )
@app.route("/doctor/user/<int:user_id>/download_summary", methods=["POST"])
def download_user_summary(user_id):
    if "doctor_id" not in session:
        flash("⚠️ Please log in as doctor.", "warning")
        return redirect(url_for("doctor_login"))
    
    user = User.query.get(user_id)
    if not user:
        flash("User not found.", "danger")
        return redirect(url_for("doctor_dashboard"))

    scans = ScanHistory.query.filter_by(user_id=user_id).order_by(ScanHistory.date.desc()).all()
    total_scans = len(scans)
    cancer_detected = sum(1 for s in scans if s.cancer_detected)

    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # ==============================
    # HEADER
    # ==============================
    pdf.setFont("Helvetica-Bold", 18)
    pdf.drawString(180, height - 50, "User Summary Report")

    pdf.setFont("Helvetica", 12)
    y = height - 100

    pdf.drawString(60, y, f"👤 Name: {user.name}")
    y -= 20
    pdf.drawString(60, y, f"🎂 Age: {user.age}")
    y -= 20
    pdf.drawString(60, y, f"📞 Contact: {user.contact}")
    y -= 20
    pdf.drawString(60, y, f"📝 Total Scans: {total_scans}")
    y -= 20
    pdf.drawString(60, y, f"⚠️ Cancer Detected: {cancer_detected} time(s)")
    y -= 30

    # ==============================
    # SCAN HISTORY TABLE
    # ==============================
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(60, y, "📊 Complete Scan History")
    y -= 20

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(60, y, "Scan ID")
    pdf.drawString(120, y, "Type")
    pdf.drawString(260, y, "Stage")
    pdf.drawString(350, y, "Confidence")
    pdf.drawString(450, y, "Date")
    y -= 15
    pdf.line(60, y, 550, y)
    y -= 20

    pdf.setFont("Helvetica", 11)

    pdf.setFont("Helvetica", 11)

    # Column X positions (well spaced)
    x_id      = 60
    x_type    = 140
    x_stage   = 340
    x_conf    = 430
    x_date    = 500

    for s in scans:
        if y < 80:
            pdf.showPage()
            y = height - 80

            # Reprint Header on new page
            pdf.setFont("Helvetica-Bold", 12)
            pdf.drawString(x_id,   y, "Scan ID")
            pdf.drawString(x_type, y, "Type")
            pdf.drawString(x_stage, y, "Stage")
            pdf.drawString(x_conf, y, "Confidence")
            pdf.drawString(x_date, y, "Date")

            y -= 15
            pdf.line(60, y, 550, y)
            y -= 20
            pdf.setFont("Helvetica", 11)

        # Trim long cancer type
        display_type = (s.cancer_type[:25] + "...") if len(s.cancer_type) > 25 else s.cancer_type

        pdf.drawString(x_id,    y, str(s.id))
        pdf.drawString(x_type,  y, display_type)
        pdf.drawString(x_stage, y, s.cancer_stage or "N/A")
        pdf.drawString(x_conf,  y, f"{s.confidence * 100:.2f}%")
        pdf.drawString(x_date,  y, s.date.strftime("%Y-%m-%d"))

        y -= 18

    # FOOTER
    pdf.setFont("Helvetica-Oblique", 10)
    pdf.drawString(60, 40, "Generated by Doctor Dashboard – Pancreatic Cancer Detection System")

    pdf.save()
    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name=f"User_{user.id}_Full_Summary.pdf",
        mimetype="application/pdf"
    )
@app.route('/doctor/mail_patient/<int:user_id>', methods=['POST'])
def mail_patient(user_id):
    if "doctor_id" not in session:
        flash("⚠️ Please log in as doctor.", "warning")
        return redirect(url_for("doctor_login"))

    user = User.query.get(user_id)
    if not user:
        flash("❌ User not found.", "danger")
        return redirect(url_for("doctor_dashboard"))

    doctor = Doctor.query.get(session['doctor_id'])   # ✅ FIX #1
    doctor_name = doctor.name
    doctor_email = doctor.email
    doctor_contact = doctor.contact

    message = request.form.get("message")

    try:
        import smtplib
        from email.mime.text import MIMEText
        from email.mime.multipart import MIMEMultipart

        sender_email = "MAIL_USERNAME"   # SMTP sender
        sender_password = "MAIL_PASSWORD"           # App Password

        msg = MIMEMultipart()
        msg["From"] = f"Dr. {doctor_name} <{doctor_email}>"  # ✅ FIX #2
        msg["To"] = user.email
        msg["Reply-To"] = doctor_email
        msg["Subject"] = f"Message from Dr. {doctor_name}"

        footer = f"""

—
This message was sent by your doctor, Dr. {doctor_name}
Pancreatic Cancer Detection Website

📧 Doctor Email: {doctor_email}
📞 Doctor Contact: {doctor_contact}

For any technical issues, please contact: yourmedicalreport@gmail.com
"""

        full_message = message + footer
        msg.attach(MIMEText(full_message, "plain"))

        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.send_message(msg)

        flash("📧 Message successfully sent to patient!", "success")

    except Exception as e:
        print("Email Error:", e)
        flash("❌ Failed to send mail.", "danger")

    return redirect(url_for('doctor_view_user', user_id=user_id))
@app.route('/doctor/chatbot', methods=['POST'])
def doctor_chatbot():
    if "doctor_id" not in session:
        return jsonify({"reply": "⚠️ Access denied. Only doctors can use this chatbot."})

    data = request.get_json()
    doctor_msg = data.get("message", "").strip()

    if not doctor_msg:
        return jsonify({"reply": "Please type a message 😊"})

    # === Fetch Database Stats for Doctor Use ===
    total_users = User.query.count()
    total_scans = ScanHistory.query.count()
    cancer_cases = ScanHistory.query.filter_by(cancer_detected=True).count()
    no_cancer_cases = total_scans - cancer_cases

    users_data = [
        {
            "id": u.id,
            "name": u.name,
            "age": u.age,
            "contact": u.contact,
            "email": u.email,
            "total_scans": len(u.scans),
            "cancer_detected": sum(1 for s in u.scans if s.cancer_detected)
        }
        for u in User.query.all()
    ]

    prompt = f"""
    You are an AI assistant exclusive for verified doctors.

    Database Summary:
    - Total Users: {total_users}
    - Total Scans: {total_scans}
    - Cancer Cases: {cancer_cases}
    - No Cancer Cases: {no_cancer_cases}

    User Records:
    {users_data}

    The doctor asked:
    "{doctor_msg}"

    Your Job:
    - Answer medically appropriate queries
    - Provide database-based insights
    - Summarize user scan history when requested
    - DO NOT give prescriptions
    - Keep answers professional and clear
    """

    try:
        model = genai.GenerativeModel("models/gemini-2.5-flash")
        response = model.generate_content(prompt)
        reply = response.text or "Sorry, I couldn't respond."

        return jsonify({"reply": reply})

    except Exception as e:
        print("Doctor Chatbot Error:", e)
        return jsonify({"reply": "⚠️ Something went wrong. Please try again later."})

from collections import Counter, defaultdict

@app.route('/admin')
def admin_panel():
    # --- Auth check ---
    if 'user_name' not in session or session['user_name'] != "Vishnu B":
        flash("🚫 Access denied. Only admin can view this page.", "danger")
        return redirect(url_for('login'))

    # --- Fetch base data ---
    users = User.query.all()
    
    users_json = []
    for u in users:
        users_json.append({
            "id": u.id,
            "name": u.name,
            "email": u.email,
            "gender": u.gender,
            "age": u.age,
            "contact": u.contact,
            "total_scans": len(u.scans),
            "cancer_detected": sum(1 for s in u.scans if s.cancer_detected),
            "no_cancer": sum(1 for s in u.scans if not s.cancer_detected)
        })
    
    doctors = Doctor.query.all()
    scans = ScanHistory.query.all()

    # --- Debug (optional) ---
    print("DEBUG: Total doctors ->", len(doctors))

    # ---------------- USER ANALYTICS ----------------
    male_count, female_count = 0, 0
    age_groups = {'20-30': 0, '30-40': 0, '40-50': 0, '50+': 0}
    cancer_cases, non_cancer_cases = 0, 0

    age_confidence = {'20-30': [], '30-40': [], '40-50': [], '50+': []}

    for s in scans:
        if s.user and s.user.age:
            age = s.user.age
            if 20 <= age < 30:
                age_confidence['20-30'].append(s.confidence)
            elif 30 <= age < 40:
                age_confidence['30-40'].append(s.confidence)
            elif 40 <= age < 50:
                age_confidence['40-50'].append(s.confidence)
            else:
                age_confidence['50+'].append(s.confidence)

    avg_confidence_by_age = {
        g: round(sum(v) / len(v), 2) if v else 0
        for g, v in age_confidence.items()
    }

    for user in users:
        total_scans = len(user.scans)
        cancer_detected = sum(1 for s in user.scans if s.cancer_detected)
        no_cancer = total_scans - cancer_detected

        gender = (user.gender or "").capitalize()
        if gender == "Male":
            male_count += 1
        elif gender == "Female":
            female_count += 1

        if 20 <= user.age < 30:
            age_groups['20-30'] += 1
        elif 30 <= user.age < 40:
            age_groups['30-40'] += 1
        elif 40 <= user.age < 50:
            age_groups['40-50'] += 1
        else:
            age_groups['50+'] += 1

        cancer_cases += cancer_detected
        non_cancer_cases += no_cancer

    # ---------------- DOCTOR ANALYTICS ----------------
    pending_doctors = Doctor.query.filter_by(status="PENDING").all()

    approved_doctors = Doctor.query.filter_by(status="APPROVED").count()
    pending_count = Doctor.query.filter_by(status="PENDING").count()
    rejected_doctors = Doctor.query.filter_by(status="REJECTED").count()

    doctor_specialization_counts = dict(
        Counter(d.specialization for d in doctors if d.specialization)
    )

    doctor_registrations = defaultdict(int)
    for d in doctors:
        doctor_registrations[d.created_at.strftime("%Y-%m-%d")] += 1

    doctor_registration_trend = dict(sorted(doctor_registrations.items()))


    
    # ---------------- RENDER ----------------
    return render_template(
        "admin.html",
        users=users,                 # used ONLY for tables
        users_json=users_json,       # used ONLY for charts
        doctors=doctors,
        pending_doctors=pending_doctors,

        approved_doctors=approved_doctors,
        pending_count=pending_count,
        rejected_doctors=rejected_doctors,

        doctor_specialization_counts=doctor_specialization_counts,
        doctor_registration_trend=doctor_registration_trend,
        avg_confidence_by_age=avg_confidence_by_age,
        male_count=male_count,
        female_count=female_count,
        age_groups=age_groups,
        cancer_cases=cancer_cases,
        non_cancer_cases=non_cancer_cases
    )

# -------------------------------
# MAIN ENTRY
# -------------------------------
# -------------------------------
# CREATE DB TABLES (ALWAYS)
# -------------------------------
with app.app_context():
    db.create_all()

# -------------------------------
# MAIN ENTRY
# -------------------------------
if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)
